### ISSUE TITLE
Server side missing indigo: Unable to load library '.../libindigo.so': Native library not found in resource path

### ISSUE THREAD

**Issue by bazitur** [epam/Indigo-ELN-v.-2.0#9]
Hi,
I managed to get the whole bundle up and running using `docker compose up`. However, I have encountered a problem regarding what seems to be an error on the side of Indigo toolkit: whenever I try to save or import a structure in the Ketcher editor, nothing seems to happen. For example, nothing changes in the reaction scheme window:
![image](https://user-images.githubusercontent.com/26185574/210172081-fd0d2aa1-b21f-4180-908b-d825242e48d3.png)
At the same time, JS browser console and terminal log the same error, [here is a link to a gist](https://gist.github.com/bazitur/493bd84839569b33899d44983aaa53f9). It seems that somehow ELN application cannot locate Indigo library.

I've tried tinkering around the code, but I wasn't able to resolve this probem. Any help would be greatly appreciated!

**Comment by HeDo88TH** [comment]
I encountered this error too. Is there a solution? @mkviatkovskii

**Comment by saurabhgayali** [comment]
> I encountered this error too. Is there a solution? @mkviatkovskii

Could you provide proper link!

**Comment by bdeadman** [comment]
I have also encountered this issue recently. I don't have a fix, but my suspicion is a problem with the BingoDB cartridge. Text, numerical and files are all saved to the DB, but the chemical structures (from Ketcher) aren't getting into the DB. As reported by others, I see the same error when attempting to save a Ketcher structure to the ELN:

2024-04-10 17:00:37 indigoeln-server-1  | java.lang.UnsatisfiedLinkError: Unable to load library '/tmp/indigo8da420a34c5340161cbe4c60a8df4dc8/libindigo.so': Native library (tmp/indigo8da420a34c5340161cbe4c60a8df4dc8/libindigo.so) not found in resource path

**Comment by denis-dzenskevich** [comment]
Fixed by https://github.com/epam/Indigo-ELN-v.-2.0/pull/15

**Comment by saurabhgayali** [comment]
the problem did not encounter in docker version.

**Comment by denis-dzenskevich** [comment]
@saurabhgayali Do you mean it's fixed now under docker? Or it never appeared under docker? If latter, I had the same error with docker until it was fixed
